### ISSUE TITLE
Inconsistent numbers of differential binding sites

### ISSUE THREAD

**Issue by ckntav** [shao-lab/MAnorm#11]
Dear MAnorm developers,

I am comparing two conditions with the following numbers of peaks:
- control condition: 64 peaks
- treated condition: 15883 peaks

I notice several abnormal behaviour:
- At the step 6 of running, I have an error message:
`ValueError: max() arg is an empty sequence`
- Then no writing output ==== Stats =====
- read_density_on_common_peaks.png is the only files in output_figures
- output_filters folder have 3 bed files with inconsistent numbers of peaks: above: 1668 peaks; below: 2906 peaks, unbiased: 6354 peaks. I would expect the number of below peaks being limited by the number of peaks in the control condition.
- The majority of below peaks comes from the treated condition set of peaks.

I'm am using Manorm version 1.2.0

Have you already encounter those issues?
Thank you in advance

**Comment by hongduosun** [comment]
MAnorm uses the common peaks between treatment and control to build the regression model, maybe the number of common peaks in not enough for this since the control condition is quite small?
Could you please paste the whole log here to find the problem?

**Comment by ckntav** [comment]
Thank you for your quick reply

Here the output of MAnorm:
`Running MAnorm v1.2.0
Command-line arguments: --p1 /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/peak_call/treated_cond/treated_cond_peaks.narrowPeak.bed --p2 /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/peak_call/ctrl_cond/ctrl_cond_peaks.narrowPeak.bed --r1 /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/alignment/treated_cond/treated_cond.sorted.dup.bed --r2 /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/alignment/ctrl_cond/ctrl_cond.sorted.dup.bed -m 0.5 -o /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/binding_diff/MCF7_HS_HSF1_30vs0
==== INFO ====
Sample 1 name = treated_cond_peaks.narrowPeak
Sample 1 peak file = /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/peak_call/treated_cond/treated_cond_peaks.narrowPeak.bed [bed]
Sample 1 read file = /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/alignment/treated_cond/treated_cond.sorted.dup.bed [bed]
Sample 1 read shift size = 100
Sample 2 name = ctrl_cond_peaks.narrowPeak
Sample 2 peak file = /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/peak_call/ctrl_cond/ctrl_cond_peaks.narrowPeak.bed [bed]
Sample 2 read file = /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/alignment/ctrl_cond/ctrl_cond.sorted.dup.bed [bed]
Sample 2 read shift size = 100
Paired-end mode: off
Window size = 2000
Summit distance cutoff = 500
Number of random simulation = 10
M-value cutoff = 0.5
P-value cutoff = 0.01
Output directory = /Users/chris/Desktop/sb_cofactor_hr/MCF7/output/chip-pipeline-GRCh38-HS/binding_diff/MCF7_HS_HSF1_treatedvctrl
==== Running ====
Step 1: Loading input data
Loading peaks of sample 1
Loading peaks of sample 2
Loading reads of sample 1
Loading reads of sample 2
Step 2: Processing peaks
Step 3: Testing the enrichment of peak overlap
Step 4: Fitting M-A normalization model on common peaks
Step 5: Normalizing all peaks
Step 6: Write output files
Traceback (most recent call last):
  File "/usr/local/bin/manorm", line 11, in <module>
    load_entry_point('MAnorm==1.2.0', 'console_scripts', 'manorm')()
  File "/usr/local/lib/python3.7/site-packages/MAnorm-1.2.0-py3.7.egg/manorm/cli.py", line 125, in main
    app.run()
  File "/usr/local/lib/python3.7/site-packages/MAnorm-1.2.0-py3.7.egg/manorm/application.py", line 174, in run
    self.output()
  File "/usr/local/lib/python3.7/site-packages/MAnorm-1.2.0-py3.7.egg/manorm/application.py", line 191, in output
    self.ma_model.ma_params)
  File "/usr/local/lib/python3.7/site-packages/MAnorm-1.2.0-py3.7.egg/manorm/plot.py", line 69, in plt_figures
    a_max = max(max(a_values), a_max)
ValueError: max() arg is an empty sequence`

**Comment by ckntav** [comment]
Thank you for your quick reply

Here is the output of MANorm:
`Running MAnorm v1.2.0

Command-line arguments: --p1 /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/peak_call/treated_cond/treated_cond_peaks.narrowPeak.bed --p2 /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/peak_call/ctrl_cond/ctrl_cond_peaks.narrowPeak.bed --r1 /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/alignment/treated_cond/treated_cond.sorted.dup.bed --r2 /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/alignment/ctrl_cond/ctrl_cond.sorted.dup.bed -m 0.5 -o /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/binding_diff/MCF7_HS_HSF1_treatedvctrl
==== INFO ====
Sample 1 name = treated_cond_peaks.narrowPeak
Sample 1 peak file = /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/peak_call/treated_cond/treated_cond_peaks.narrowPeak.bed [bed]
Sample 1 read file = /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/alignment/treated_cond/treated_cond.sorted.dup.bed [bed]
Sample 1 read shift size = 100
Sample 2 name = ctrl_cond_peaks.narrowPeak
Sample 2 peak file = /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/peak_call/ctrl_cond/ctrl_cond_peaks.narrowPeak.bed [bed]
Sample 2 read file = /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/alignment/ctrl_cond/ctrl_cond.sorted.dup.bed [bed]
Sample 2 read shift size = 100
Paired-end mode: off
Window size = 2000
Summit distance cutoff = 500
Number of random simulation = 10
M-value cutoff = 0.5
P-value cutoff = 0.01
Output directory = /Users/chris/Desktop/hsproj/MCF7/output/chip-pipeline-GRCh38-HS/binding_diff/MCF7_HS_HSF1_treatedvctrl
==== Running ====
Step 1: Loading input data
Loading peaks of sample 1
Loading peaks of sample 2
Loading reads of sample 1
Loading reads of sample 2
Step 2: Processing peaks
Step 3: Testing the enrichment of peak overlap
Step 4: Fitting M-A normalization model on common peaks
Step 5: Normalizing all peaks
Step 6: Write output files
Traceback (most recent call last):
  File "/usr/local/bin/manorm", line 11, in <module>
    load_entry_point('MAnorm==1.2.0', 'console_scripts', 'manorm')()
  File "/usr/local/lib/python3.7/site-packages/MAnorm-1.2.0-py3.7.egg/manorm/cli.py", line 125, in main
    app.run()
  File "/usr/local/lib/python3.7/site-packages/MAnorm-1.2.0-py3.7.egg/manorm/application.py", line 174, in run
    self.output()
  File "/usr/local/lib/python3.7/site-packages/MAnorm-1.2.0-py3.7.egg/manorm/application.py", line 191, in output
    self.ma_model.ma_params)
  File "/usr/local/lib/python3.7/site-packages/MAnorm-1.2.0-py3.7.egg/manorm/plot.py", line 69, in plt_figures
    a_max = max(max(a_values), a_max)
ValueError: max() arg is an empty sequence
`

**Comment by hongduosun** [comment]
It is probable that the number of common/overlapping peaks is  0, can you use `bedtools intersect` to check it?

**Comment by ckntav** [comment]
After using `bedtools intersect`, it shows that there are 64 common peaks between my two conditions. Actually, all my control peaks are included in my treated peaks.
![image](https://user-images.githubusercontent.com/36061268/68028253-cf975a80-fc8a-11e9-85ca-5349d824de4d.png)

Does it prevent the linear regression from being performed?

**Comment by hongduosun** [comment]
It does not prevent the regression but it prevents the later normalizing procedure because there are no unique peaks in control to be normalized.  I wonder why there is so limited number of peaks in control compared to treatment? Are they both from the same histone modification/TF ChIP-seq?

**Comment by ckntav** [comment]
Yes, these two samples are from the same TF ChIP-seq, HSF1. There is a limited number of peaks because HSF1 is mostly in the cytoplasm before stimulation.

Thanks a lot for your support!
