### ISSUE TITLE
Difference between MAnorm and MAnorm2

### ISSUE THREAD

**Issue by ckntav** [shao-lab/MAnorm#12]
Hello,

A second version of MAnorm have been developped.
What are the major differences between those two softwares?
Do you suggest using one instead of the other?

Thank you in advance

**Comment by hongduosun** [comment]
MAnorm is designed for comparison of 2 conditions without replicates, 1 vs 1, and MAnorm2 is for comparing samples with replicates. Always use MAnorm2 when you have replicates.

**Comment by ckntav** [comment]
Does MAnorm2 suitable to use without replicates? Would it give the same results as MAnorm?
In order to be consistent in further analysis, I would like to exclusively use one or another.
Thank you

**Comment by hongduosun** [comment]
MAnorm2 incorporates the variance among replicates to fit the mean-variance curve and gives a comprehensive statistic.  The results won't be the same as MAnorm.  Use MAnorm when you have no replicates.

**Comment by ckntav** [comment]
Thank you for your reply
