### ISSUE TITLE
The influence of read number on MAnorm result.

### ISSUE THREAD

**Issue by a091601** [shao-lab/MAnorm#13]
Due to the library construction and filiter reads after mapping(low MAPQ), we get two samples: WT_TFs and KO_TFs, but the reads using in MAnorm are 15M and 23M seperately(actually the raw reads before mapping are both 25M). Thus, what i want to ask is if and how the reads number influence the result of MAnorm?

**Comment by hongduosun** [comment]
The unbalanced total reads number is not a big issue as long as these two samples have a similar quality or signal-to-noise ratio, the percentage of how many reads falling into peak regions will be a good assessment.
