### ISSUE TITLE
index error 

### ISSUE THREAD

**Issue by yysheep2020** [shao-lab/MAnorm#17]
Hi dear MAnorm author:

I have run the Manorm based on the output from ENCODE-atac pipeline. And it shows the index error. Thanks for checking this for me...
INFO     07/02/2020 08:53: # MAnorm Arguments:
INFO     07/02/2020 08:53: # Peaks file of sample1 = 2A.narrowPeak
INFO     07/02/2020 08:53: # Peaks file of sample2 = 2B.narrowPeak
INFO     07/02/2020 08:53: # Reads file of sample1 = 2A_R1_paired.bam
INFO     07/02/2020 08:53: # Reads file of sample2 = 2B_R1_paired.bam
INFO     07/02/2020 08:53: # Reads shift size of sample1 = 100
INFO     07/02/2020 08:53: # Reads shift size of sample2 = 100
INFO     07/02/2020 08:53: # Peak width to extend from summit = 1000
INFO     07/02/2020 08:53: # Summit-to-summit distance cutoff = 500
INFO     07/02/2020 08:53: # Output directory = output_dir
INFO     07/02/2020 08:53: Step1: Loading input data
INFO     07/02/2020 08:53: 38225 peaks are loaded from 2A.narrowPeak
INFO     07/02/2020 08:53: 28199 peaks are loaded from 2B.narrowPeak
Traceback (most recent call last):
  File "/scg/apps/software/manorm/1.1.4/bin/manorm", line 11, in <module>
    load_entry_point('MAnorm==1.1.4', 'console_scripts', 'manorm')()
  File "/scg/apps/software/manorm/1.1.4/manorm/cmdline.py", line 95, in main
    full_output=full_output, name1=name1, name2=name2, output_name=output_name)
  File "/scg/apps/software/manorm/1.1.4/manorm/workflow.py", line 36, in main
    ma.load_reads(reads_file1, reads_file2, shift_size1, shift_size2)
  File "/scg/apps/software/manorm/1.1.4/manorm/core.py", line 32, in load_reads
    self.reads1 = Reads(reads_file1, self.name1, shift_size1)
  File "/scg/apps/software/manorm/1.1.4/manorm/lib/read.py", line 22, in __init__
    self.load_reads(path, shift)
  File "/scg/apps/software/manorm/1.1.4/manorm/lib/read.py", line 30, in load_reads
    chrom, start, end, strand = fields[0], int(fields[1]), int(fields[2]), fields[5]
IndexError: list index out of range

**Comment by hongduosun** [comment]
Hi, MAnorm 1.1.4 only supports the BED format for the reads files. Please update to 1.2.0 or more recent versions to use BAM files.

**Comment by hongduosun** [comment]
BTW， if you are analyzing ATAC-Seq data, the `shifitsize` parameter should be set to 0.
