### ISSUE TITLE
Question regarding window size

### ISSUE THREAD

**Issue by AntonioAhn** [shao-lab/MAnorm#20]
Dear MAnorm team, 

Thank you for MAnorm. Its been really helpful for looking at differential peaks. 
Could i please ask a question regarding selecting the correct window size for my H3K27ac ChIPseq data? 

In the manual, it says "Window size to count reads and calculate read densities. 2000 is recommended for sharp histone marks like H3K4me3 and H3K27ac, and 1000 for TFs or DNase-seq. Default: 2000" and in the paper it also says "Here the window size should be comparable to the median length of ChIP-enriched regions". The average fragment length for my H3K27ac ChIP-seq data is 350 bps (calculated using cross-correlation analysis). Would this suggest I should use a window size of 500? 

I have tried three windows: 1) -w 2000, 2) -w 1000 and 3) -w 500. The number of differential peaks significantly increases with dropping the window size from 1) 22458 peaks, 2) 29500 peaks and 3) 35242 peaks, respectively. With this in view, I thought a window of 500 is better however I have found that many of the peaks found with -w 2000 and -w 1000 are not found with -w 500. 

For instance, in this first IGV screenshot shows a differential peak only with **-w 2000**. The order the of track is:
1) treatment sample (bigwig)(blue)
2) treatment sample (macs2 peaks) (blue)
3) control sample (bigwig) (red)
4) control sample (macs2 peaks) (red)
5) manorm window 2000
6) manorm window 1000
7) manorm window 500
<img width="1150" alt="window2000_only" src="https://user-images.githubusercontent.com/18894867/93845973-bfe79100-fcf6-11ea-9995-458480e39ae5.png">

In this second IGV screenshot, a differential peak is only found with **-w 1000**
<img width="1149" alt="window1000_only" src="https://user-images.githubusercontent.com/18894867/93846240-97ac6200-fcf7-11ea-8a6d-19d45f432ef4.png">

And in this third IGV screenshot, a differential peak only found with **-w 500**
<img width="1146" alt="window500_only" src="https://user-images.githubusercontent.com/18894867/93846286-b4489a00-fcf7-11ea-8982-34a2b9eaba8d.png">

Would you recommend using all three window parameters separately and finding the common/consensus peaks?

**Comment by hongduosun** [comment]
Hi, thanks for using MAnorm!
The fragment size of the ChIP-seq library has a limited relationship with the length of the peak region.  A fragment size 350bp on average does not mean the average peak length is 500bp or 100bp or even longer.
The proper value of -w should match the average/median length of your peak regions. If -w is too large, it may include many flanking background regions and if too small, only the most enriching part within a peak is covered.
For your first example, -w 2000 is suitable as the peak length is about 2000bp. The second example is quite similar except that the peak length/-w is about 1000bp. But -w 500 is definitely too small for all the 3 examples as it is not sufficient to cover the main peak body. 
It is better to check the length distribution of all the peak regions and see if most situations are like example 1 or example 2.

**Comment by AntonioAhn** [comment]
Hi Hyaden! 

Thanks so much for the feedback! I obtained the peak lengths (end minus start position) from the macs2 narrowpeak output file. The peak median length is 765 bps (for control) and 903 bps (for treatment). The boxplot and density distribution plot also shows this (contol=black, treatment=orange). 
So with this in view, I guess -w 1000 would be more appropriate, or do you suggest going with the actual median length? 

I was also wondering since peaks such as in example 1 of my previous post would be missed with -w 1000, but not with -w 2000, do you suggest doing both and somehow combining the manorm output xls file ? 

![boxplot_manorm](https://user-images.githubusercontent.com/18894867/93874057-e3c2cb00-fd26-11ea-95be-b5a73dd37d6d.png)
![densityplot_manorm](https://user-images.githubusercontent.com/18894867/93874073-e9201580-fd26-11ea-8d4f-2d61f644dc78.png)

**Comment by hongduosun** [comment]
Yes, -w 1000 would be better here. I don't recommend to do both and combine them. Instead, you can check if the M value in example 1 when using -w 1000 is also positive but is just not big enough to pass the M value cutoff? If so, you can use a loose cutoff (maybe M value corresponding to a 1.5-fold ?) to get more differential regions.

**Comment by AntonioAhn** [comment]
Thanks so much for your help !! Appreciate it greatly!
