### ISSUE TITLE
Job running for ever on cluster

### ISSUE THREAD

**Issue by YannVRB** [shao-lab/MAnorm#24]
Hi,

It has been now few days that manorm is stuck on the cluster at this step (processing peaks), has anyone got this issue? It doesn't seem to run out of memory or crash, it just keeps running:
![image](https://user-images.githubusercontent.com/69206510/135938069-6ef0ff4c-45e7-4e62-8850-6858a4a1b80e.png)

Thanks

**Comment by hongduosun** [comment]
Hi, the input peak files seem to be bedgragh .bg genome tracks and the number of peaks are extremely high. So I guess you somehow gave MAnorm the whole genome instead of the peak regions only?
