### ISSUE TITLE
Heatmap output. [Feature request]

### ISSUE THREAD

**Issue by AlicePsyche** [shao-lab/MAnorm#4]
Hi, there 

Sorry for the interruption. MAnorm worked well for my problems, many thanks for you :)  I just wondering could you please add an additional output file of differential peaks heatmap. Normally a heatmap is a more direct visualization way. 

Something like this?
![Differential heatmap](https://image.ibb.co/icFkJH/111111111.jpg)

Thanks in advance.

**Comment by hongduosun** [comment]
@AlicePsyche With the coefficients MAnorm outputs, you can draw the heatmap manually or with some existing tools like deeptools. I'm making note of it but the feature isn't guaranteed to be added.

**Comment by AlicePsyche** [comment]
Thanks for your reply! I know I can generate the heatmap by myself, I just thought that it would be better if the heatmap could be involved. Some of my colleagues who are not so familiar with programming dropped this tools just because that the output formats are not what they expected. 

Anyway, thanks for your great work.

Cheers

**Comment by haydensun** [comment]
@AlicePsyche Thanks for your suggestion, and I'll add the feature in the next major update.

**Comment by hongduosun** [comment]
This feature is not considered to be added. Close for now.
