### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Yippee0** [shao-lab/MAnorm#5]
INFO     03/10/2018 11:21: # MAnorm Arguments:
INFO     03/10/2018 11:21: # Peaks file of sample1 = D872_raw_peaks.bed
INFO     03/10/2018 11:21: # Peaks file of sample2 = DZ_raw_peaks.bed
INFO     03/10/2018 11:21: # Reads file of sample1 = D872_reads_4.bed
INFO     03/10/2018 11:21: # Reads file of sample2 = DZ_reads_4.bed
INFO     03/10/2018 11:21: # Reads shift size of sample1 = 125
INFO     03/10/2018 11:21: # Reads shift size of sample2 = 125
INFO     03/10/2018 11:21: # Peak width to extend from summit = 1000
INFO     03/10/2018 11:21: # Summit-to-summit distance cutoff = 500
INFO     03/10/2018 11:21: # Output directory = MAnorm
INFO     03/10/2018 11:21: Step1: Loading input data
INFO     03/10/2018 11:21: 161613 peaks are loaded from D872_raw_peaks.bed
INFO     03/10/2018 11:21: 160980 peaks are loaded from DZ_raw_peaks.bed
Traceback (most recent call last):
  File "/ifs2/home/qzhang/Soft/Python-2.7.2/bin/manorm", line 11, in <module>
    sys.exit(main())
  File "/ifs2/home/qzhang/Soft/Python-2.7.2/lib/python2.7/site-packages/manorm/cmdline.py", line 95, in main
    full_output=full_output, name1=name1, name2=name2, output_name=output_name)
  File "/ifs2/home/qzhang/Soft/Python-2.7.2/lib/python2.7/site-packages/manorm/workflow.py", line 33, in main
    ma.load_reads(reads_file1, reads_file2, shift_size1, shift_size2)
  File "/ifs2/home/qzhang/Soft/Python-2.7.2/lib/python2.7/site-packages/manorm/core.py", line 32, in load_reads
    self.reads1 = Reads(reads_file1, self.name1, shift_size1)
  File "/ifs2/home/qzhang/Soft/Python-2.7.2/lib/python2.7/site-packages/manorm/lib/read.py", line 22, in __init__
    self.load_reads(path, shift)
  File "/ifs2/home/qzhang/Soft/Python-2.7.2/lib/python2.7/site-packages/manorm/lib/read.py", line 30, in load_reads
    chrom, start, end, strand = fields[0], int(fields[1]), int(fields[2]), fields[5]
IndexError: list index out of range

reads file was created by bedtools bamtobed and cut 1-3 & strand.
peaks was macs2 created .xls. 
whether reads file need to be 6 tab bed files ? but the README said that reads files need chr start end strand if fine ?

**Comment by Yippee0** [comment]
Besides, how did you creat the reads file? thank very much for your answer!!!

**Comment by Yippee0** [comment]
The problem have be solved, the reads files was the raw bam covert bed file, then it works!

**Comment by hongduosun** [comment]
Formats of reads file MAnorm supports:
http://manorm.readthedocs.io/en/latest/tutorial.html#format-of-reads-file
BED format:
https://genome.ucsc.edu/FAQ/FAQformat.html#format1
