### ISSUE TITLE
Macs2 format

### ISSUE THREAD

**Issue by liehu232** [shao-lab/MAnorm#6]
MAnorm always tread macs2 as bed

I think the problem is the way determine input format in MAnorm/manorm/lib/peak.py load_peaks,

**Comment by hongduosun** [comment]
Currently MACS2 format is not supported, I'm rewriting the peak parser to support more formats (macs2 xls, narrowPeak, boardPeak etc.)
For temporal solution, you could adapt it into 4-columns tab-seperated format (chr, start, end, summit)
See http://manorm.readthedocs.io/en/latest/tutorial.html#input-format

**Comment by hongduosun** [comment]
MAnorm v1.3.0 now supports the MACS2 format.
