### ISSUE TITLE
No Figure output

### ISSUE THREAD

**Issue by crg-eilslabs** [shao-lab/MAnorm#7]
Dear all,

I am using MAnorm version 1.1.3. The code runs fine and gives a the output files, except that there are no figures in the output_figures folder.
I used the bioconda version of MAnorm.

Any idea what the probem might be?
Thanks,
Carl

**Comment by hongduosun** [comment]
@crg-eilslabs Is there any error information or could u please paste the log file?

**Comment by hongduosun** [comment]
Please update to v1.1.4 (#8)
